Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp/bionic64"
  
	config.vm.define "tzanchiS" do |tzanchiS|
	  tzanchiS.vm.box = "debian/bookworm64"
	  tzanchiS.vm.hostname = "tzanchiS"
	  tzanchiS.vm.network "private_network", ip: "192.168.56.110"

	  tzanchiS.vm.synced_folder "./config", "/config"
  
	  tzanchiS.vm.provider "virtualbox" do |vb|
		vb.memory = "1024"
		vb.cpus = 1
	  end
  
	  tzanchiS.vm.provision "shell", inline: <<-SHELL
	    sudo apt-get update 
		sudo apt-get upgrade
		sudo apt-get install -y curl net-tools apt-transport-https ca-certificates gnupg
		curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110" sh -
		mkdir -p /etc/apt/keyrings
		curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
		sudo chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg # allow unprivileged APT programs to read this keyring
		echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
		sudo chmod 644 /etc/apt/sources.list.d/kubernetes.list   # helps tools such as command-not-found to work correctly
		sudo apt-get update
		sudo apt-get install -y kubectl
		sudo chown -R $USER /etc/rancher/
		kubectl create -f /config/app1.yaml
		kubectl create -f /config/app2.yaml
		kubectl create -f /config/app3.yaml
	  SHELL
	end
end
  