Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp/bionic64"
  
	config.vm.define "lwidmerS" do |server|
	  server.vm.box = "debian/bookworm64"
	  server.vm.hostname = "lwidmerS"
	  server.vm.network "private_network", ip: "192.168.56.110"
	  server.vm.synced_folder "./token", "/token"
  
	  server.vm.provider "virtualbox" do |vb|
		vb.memory = "1024"
		vb.cpus = 1
	  end
  
	  server.vm.provision "shell", inline: <<-SHELL
	    sudo apt-get update 
		sudo apt-get upgrade
		sudo apt-get install -y curl net-tools
		curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110" sh -
		sudo cat /var/lib/rancher/k3s/server/node-token > /token/node-token
	  SHELL
	end
  
	config.vm.define "lwidmerSW" do |worker|
	  worker.vm.box = "debian/bookworm64"
	  worker.vm.hostname = "lwidmerSW"
	  worker.vm.network "private_network", ip: "192.168.56.111" 
	  worker.vm.synced_folder "./token", "/token"
	  
	  worker.vm.provider "virtualbox" do |vb|
		vb.memory = "1024"
		vb.cpus = 1
	  end
  
	  worker.vm.provision "shell", inline: <<-SHELL
		while [ ! -f /token/node-token ]; do
		  echo "Waiting for K3S token..."
		  sleep 5
		done
		sudo apt-get update 
		sudo apt-get upgrade
		sudo apt-get install -y curl net-tools
		curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.111" K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=`cat /token/node-token` sh -
	  SHELL
	end
end
  