Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp/bionic64"
  
	config.vm.define "lwidmerS" do |server|
	  server.vm.box = "debian/bookworm64"
	  server.vm.hostname = "lwidmerS"
	  server.vm.network "private_network", ip: "192.168.56.110"
	  server.vm.synced_folder "./token", "/token"
  
	  server.vm.provider "virtualbox" do |vb|
		vb.memory = "1024"
		vb.cpus = 1
	  end
  
	  server.vm.provision "shell", inline: <<-SHELL
	    sudo apt-get update 
		sudo apt-get upgrade
		sudo apt-get install -y curl net-tools apt-transport-https ca-certificates gnupg
		curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110" sh -
		sudo cat /var/lib/rancher/k3s/server/node-token > /token/node-token
		mkdir -p /etc/apt/keyrings
		curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
		sudo chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg # allow unprivileged APT programs to read this keyring
		echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
		sudo chmod 644 /etc/apt/sources.list.d/kubernetes.list   # helps tools such as command-not-found to work correctly
		sudo apt-get update
		sudo apt-get install -y kubectl
	  SHELL
	end
  
	config.vm.define "lwidmerSW" do |worker|
	  worker.vm.box = "debian/bookworm64"
	  worker.vm.hostname = "lwidmerSW"
	  worker.vm.network "private_network", ip: "192.168.56.111" 
	  worker.vm.synced_folder "./token", "/token"
	  
	  worker.vm.provider "virtualbox" do |vb|
		vb.memory = "1024"
		vb.cpus = 1
	  end
  
	  worker.vm.provision "shell", inline: <<-SHELL
		while [ ! -f /token/node-token ]; do
		  echo "Waiting for K3S token..."
		  sleep 5
		done
		sudo apt-get update 
		sudo apt-get upgrade
		sudo apt-get install -y curl net-tools apt-transport-https ca-certificates gnupg
		curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.111" K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=`cat /token/node-token` sh -
		mkdir -p /etc/apt/keyrings
		curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
		sudo chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg # allow unprivileged APT programs to read this keyring
		echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
		sudo chmod 644 /etc/apt/sources.list.d/kubernetes.list   # helps tools such as command-not-found to work correctly
		sudo apt-get update
		sudo apt-get install -y kubectl
	  SHELL
	end
end
  