apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
      - name: app-one-container
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
