apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-two
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
      - name: app-two-container
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
