apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app3-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: app3-container
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
