# app1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

---
# app2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

---
# app3
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-three
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-three
  template:
    metadata:
      labels:
        app: app-three
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
