apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app2-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2-container
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
